# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReceiptOrganizer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReceiptOrganizer
  pod 'AlamofireImage'
  pod 'Parse' 
	

  target 'ReceiptOrganizerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReceiptOrganizerUITests' do
    # Pods for testing
  end

end
